### ISSUE TITLE
[feature] User Info API

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#10]
### 어떤 코드를 작성중인지 작성해주세요.
유저정보 api
## To-Do

-   [ ] todo1 닉네임 중복확인
-   [ ] todo2 데이터 받아서 users 테이블에 넣기
-   [ ] todo2 프로필 이미지(url) 받아서 넣기
