### ISSUE TITLE
[feature] Login API

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#15]
### 어떤 코드를 작성중인지 작성해주세요.
로그인 기능 API
## To-Do

-   [ ] todo1 테이블에서 유저정보 가져와서 로그인 시켜주기
-   [ ] todo2 실시간 유효성 검사
-   [ ] todo3 로그인시 유저 로그인 상태 전역으로 관리
-   [ ] todo4 닉네임
-   [ ] todo5 이메일 
-   [ ] todo6 로그인 상태
-   [ ] todo7 프로필 이미지
