### ISSUE TITLE
[fix] Mypage 

### ISSUE THREAD

**Issue by tpring** [final-semicolon/div#162]
## To-Do

- [x] 카드 게시글 댓글 숫자 카운팅 
 
- [x] 필터 게시글, 댓글, 초기화

- [x] 필터 게시글, 댓글 외부 누르면 닫히기

- [x] 필터 버튼 배경색 바꾸기
