### ISSUE TITLE
[feature] Header UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#17]
### 어떤 코드를 작성중인지 작성해주세요.
헤더 만들기 (공용 컴포넌트)
## To-Do

-   [x] todo1 로고 자리 만들기
-   [x] todo2 홈, 포럼, Q&A, 아카이브, 공지 네비게이션 바 만들기
-   [x] todo3 검색 아이콘 넣기
-   [ ] todo4 비로그인: 로그인 회원가입 뜨게
-   [ ] todo5 로그인: 마이페이지(프로필 사진), 로그아웃 뜨게
-   [ ] todo6 (선택) 알람
