### ISSUE TITLE
[feature] Main Page UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#19]
### 어떤 코드를 작성중인지 작성해주세요.
메인페이지 UI 
## To-Do

-   [ ] todo 외부링크 div
-   [ ] todo 각각 포스트 페이지로 이동하는 버튼 + 이미지
-   [ ] todo 베스트 포럼 페이지
-   [ ] todo 실시간 포럼 페이지
-   [ ] todo 실시간 Q&A페이지
-   [ ] todo 실시간 아카이브 페이지
-   [ ] todo 태그 탐색 캐러샐
-   [ ] todo 공지사항 div
-   [ ] todo <div> 서비스 소개글
