### ISSUE TITLE
[REFACTOR] Detail page 최적화

### ISSUE THREAD

**Issue by Floweringworld** [final-semicolon/div#194]
### 어떤 코드를 작업 중인지 작성해주세요.
 Detail page 최적화
추가로 필요한 부분 있으면 작업

## To-Do

-   [ ] todo 필요없는 태그 삭제
-   [ ] todo 컨포넌트 분리
-   [ ] todo React Hook 정리
