### ISSUE TITLE
[feature] Search UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#21]
### 어떤 코드를 작성중인지 작성해주세요.
검색창 UI
## To-Do

-   [ ] todo 최상단 {params} 검색 결과 표시
-   [ ] todo 전체글, 포럼, Q&A, 아카이브 sorting UI
-   [ ] todo 최신순, 좋아요순, 북마크순 sorting UI
-   [ ] todo 게시글 보여주는 div
-   [ ] todo 검색창용 게시글 카드 만들기
-   [ ] todo 검색중 스켈레톤 만들기
