### ISSUE TITLE
[FIX] missing parts on the upsert page

### ISSUE THREAD

**Issue by YCDM03** [final-semicolon/div#236]
### 무슨 코드를 수정 중인지 설명을 적어주세요
디자인 시안과 비교하여 누락 된 부분 수정

## To-Do

-   [x] 유효성 검사 에러 메세지 출력 방식 변경
-   [x] 셀렉트 박스 카테고리 명칭 아카이브 -> 라이브러리로 변경
-   [x] 셀렉트 박스 포럼 카테고리 화살표 아이콘 추가
