### ISSUE TITLE
[feature] Mypage UI MyActivities

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#24]
### 어떤 코드를 작성중인지 작성해주세요.
마이페이지 내 활동
## To-Do

-   [ ] todo 최상단에 내가 쓴 글, 좋아요 한 글, 북마크 한 글을 이동할수 있는 네비게이션 바가 있습니다. 주의해 주세요.
-   [ ] todo 내가 쓴 글에서는 게시글밖에 안보입니다 게시글 ui를 공용 컴포넌트로 만들어 주세요
-   [ ] todo 좋아요 한 글과 북마크 한 글은 댓글도 표시됩니다 댓글 표시  ui를 공용 컴포넌트로 만들어 주세요

-   [ ] todo
-   [ ] todo
-   [ ] todo
