### ISSUE TITLE
[feature] forum detail page fix

### ISSUE THREAD

**Issue by Floweringworld** [final-semicolon/div#250]
### 어떤 코드를 작업 중인지 작성해주세요.
댓글& 대댓글 갯수 
대댓글 수정 모달 순서 변경
대댓글 버튼 스타일링 수정

## To-Do

-   [ ] todo 댓글 & 대댓글 갯수 수정
-   [ ] todo 대댓글 수정 모달 순서 변경
-   [ ] todo 대댓글 버튼 스타일리 수정
