### ISSUE TITLE
[feature] forum detail page styling&fix

### ISSUE THREAD

**Issue by Floweringworld** [final-semicolon/div#275]
### 어떤 코드를 작업 중인지 작성해주세요.
forum detail page 전체적인 스타일링 수정

## To-Do

-   [ ] todo 마크다운에디터 테두리 수정
-   [ ] todo 댓글 수정 취소 및 입력 취소 시 모달 작업
-   [ ] todo 댓글 수정 시 모달창 삭제
