### ISSUE TITLE
[feature] Forum Detail Page UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#35]
### 어떤 코드를 작성중인지 작성해주세요.
포럼 디테일 페이지
## To-Do

-   [ ] todo 뒤로가기 버튼 ( 포럼 리스트로 가기)
-   [ ] todo 게시글 ui만들기
-   [ ] todo 태그 위치 빼먹지 마세용
-   [ ] todo 쓴 댓글 ui만들기
-   [ ] todo 댓글 작성 (입력창) ui만들기
-   [ ] todo 대댓글 표시ui 만들기
-   [ ] todo 대댓글 작성창 만들기
