### ISSUE TITLE
[FIX]qna detail error fix

### ISSUE THREAD

**Issue by YCDM03** [final-semicolon/div#380]
## To-Do

-   [x] 질문 글 북마크 요청 경로 수정
-   [x] 답변 글 정렬 필터 refetch하도록 기능 변경
-   [x] 공유하기 버튼 수정
-  [x] qna detail 글 삭제 수정시 qna게시판 쿼리 키 무효화
