### ISSUE TITLE
[feature] Archiving Detail Page UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#39]
### 어떤 코드를 작성중인지 작성해주세요.
아카이브 디테일 페이지 UI
## To-Do

-   [ ] 최상단 헤더 아래 뒤로가기 버튼을 구현해주세요
-   [ ] 제목 밑에 상단 유저 정보 div를 만들어주세요
-   [ ] 마크 다운 작성한 코드를 보여주는 div를 따로 구현해주세요
