### ISSUE TITLE
[feature] User Info UI

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#8]
### 어떤 코드를 작성중인지 작성해주세요.
유저 정보 UI
## To-Do

-   [ ] todo1 닉네임 필수 + 중복확인 버튼
-   [ ] todo2 프로필 사진 받기
-   [ ] todo3 깃허브 링크 칸
-   [ ] todo4 자기 소개
-   [ ] todo5 가입하기 버튼
