### ISSUE TITLE
[feature] Auth User API

### ISSUE THREAD

**Issue by JvnKim** [final-semicolon/div#9]
### 어떤 코드를 작성중인지 작성해주세요.
인증 인가 API
## To-Do

-   [ ] todo1 이메일 비밀번호 받아서 auth.user 테이블에 저장
-   [ ] todo2 실시간 유효성검사
-   [ ] 닉네임 중복확인 검사
-   [ ] 약관 동의시 가입하기 나오게
